--CRIANDO UMA TABELA DE PRODUTOS
CREATE TABLE PRODUTO(
	ID				UNIQUEIDENTIFIER	PRIMARY KEY,
	NOME			VARCHAR(50)			NOT NULL,
	DESCRICAO		VARCHAR(255)		NOT NULL,
	PRECO			DECIMAL(10,2)		NOT NULL,	
	QUANTIDADE		INT					NOT NULL,
	DATACADASTRO	DATETIME			NOT NULL,
	ATIVO			BIT					NOT NULL);
GO

--CADASTRANDO PRODUTOS
INSERT INTO PRODUTO
	(ID, NOME, DESCRICAO, PRECO, QUANTIDADE, DATACADASTRO, ATIVO)
	VALUES
		(NEWID(), 'Notebook HP', 'Core i7 8GB SSD', 4599.99, 10, GETDATE(), 1),
		(NEWID(), 'Mouse Gamer', 'Mouse optico para jogos', 99.99, 25, GETDATE(), 1),
		(NEWID(), 'Teclado Microsoft', 'Teclado ergonômico', 199.99, 15, GETDATE(), 1),
		(NEWID(), 'Playstation 5', 'Console PS5 Slim com 2 Jogos', 3999.99, 30, GETDATE(), 1),
		(NEWID(), 'Xbox Series X', 'Console Xbox com 2 Jogos', 3599.99, 20, GETDATE(), 1);
GO

--CONSULTANDO OS PRODUTOS CADASTRADOS
SELECT
	ID, NOME, DESCRICAO, PRECO, QUANTIDADE, DATACADASTRO, ATIVO
FROM PRODUTO
WHERE ATIVO = 1
ORDER BY NOME;