# Documentação da ação Azure Web Apps Deploy: https://github.com/Azure/webapps-deploy
# Mais ações do GitHub para Azure: https://github.com/Azure/actions

name: Build e Deploy do app ASP.Net Core para Azure Web App - ProdutosAppCoti

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Compilar aplicação
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Fazer checkout do código-fonte
        uses: actions/checkout@v4

      - name: Configurar .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Compilar com dotnet
        run: dotnet build --configuration Release

      - name: Executar testes unitários
        run: dotnet test --configuration Release --no-build --collect:"XPlat Code Coverage"
        
      - name: Publicar com dotnet
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Enviar artefato para o job de deploy
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    name: Fazer deploy da aplicação
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Necessário para solicitar o JWT
      contents: read  # Necessário para actions/checkout

    steps:
      - name: Baixar artefato do job de build
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Fazer login na Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CB036BEE59BD49EC9EC1BABD8E96DD4A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1151782BC716476BAB102625661CB2E4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_961CD047C43C4A31A26E937ADE17A0A9 }}

      - name: Fazer deploy no Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ProdutosAppCoti'
          slot-name: 'Production'
          package: .
